export type AssetStatus = 'Available' | 'Assigned' | 'Faulty' | 'Retired';
export type AssetCategory =
  | 'Laptop' |'Desktop' |'Monitor' |'Printer' |'Networking' |'Accessory' |'Server' |'Phone';

export interface Asset {
  id: string;
  assetTag: string;
  name: string;
  category: AssetCategory;
  serialNumber: string;
  purchaseDate: string;
  status: AssetStatus;
  location: string;
  assignedTo?: string;
  assignedToId?: string;
  department?: string;
  notes?: string;
}

export interface Assignment {
  id: string;
  assetId: string;
  assetTag: string;
  assetName: string;
  category: AssetCategory;
  staffName: string;
  staffId: string;
  department: string;
  dateAssigned: string;
  expectedReturn: string;
  status: 'Active' | 'Returned' | 'Overdue';
  returnedDate?: string;
  notes?: string;
}

export interface AuditLog {
  id: string;
  timestamp: string;
  action: 'Added' | 'Assigned' | 'Returned' | 'Updated' | 'Deleted' | 'Flagged';
  assetTag: string;
  assetName: string;
  performedBy: string;
  details: string;
}

export const ASSETS: Asset[] = [
  {
    id: 'asset-001',
    assetTag: 'IT-LT-0041',
    name: 'Dell Latitude 5540',
    category: 'Laptop',
    serialNumber: 'DLAT5540-2024-0041',
    purchaseDate: '2024-03-15',
    status: 'Assigned',
    location: 'Floor 3 — Engineering',
    assignedTo: 'Marcus Osei',
    assignedToId: 'EMP-1042',
    department: 'Engineering',
  },
  {
    id: 'asset-002',
    assetTag: 'IT-LT-0042',
    name: 'Dell Latitude 5540',
    category: 'Laptop',
    serialNumber: 'DLAT5540-2024-0042',
    purchaseDate: '2024-03-15',
    status: 'Available',
    location: 'IT Storage Room A',
  },
  {
    id: 'asset-003',
    assetTag: 'IT-LT-0043',
    name: 'MacBook Pro 14"',
    category: 'Laptop',
    serialNumber: 'C02XG2JHJGH5',
    purchaseDate: '2024-01-20',
    status: 'Assigned',
    location: 'Floor 2 — Design',
    assignedTo: 'Priya Nair',
    assignedToId: 'EMP-0987',
    department: 'Design',
  },
  {
    id: 'asset-004',
    assetTag: 'IT-LT-0044',
    name: 'Lenovo ThinkPad X1 Carbon',
    category: 'Laptop',
    serialNumber: 'LNV-X1C-2023-0044',
    purchaseDate: '2023-11-08',
    status: 'Faulty',
    location: 'IT Repair Bay',
    notes: 'Battery not charging — sent to vendor',
  },
  {
    id: 'asset-005',
    assetTag: 'IT-DT-0021',
    name: 'HP EliteDesk 800 G9',
    category: 'Desktop',
    serialNumber: 'HPDT800G9-0021',
    purchaseDate: '2023-07-12',
    status: 'Assigned',
    location: 'Floor 1 — Finance',
    assignedTo: 'Sandra Kimani',
    assignedToId: 'EMP-0321',
    department: 'Finance',
  },
  {
    id: 'asset-006',
    assetTag: 'IT-DT-0022',
    name: 'HP EliteDesk 800 G9',
    category: 'Desktop',
    serialNumber: 'HPDT800G9-0022',
    purchaseDate: '2023-07-12',
    status: 'Available',
    location: 'IT Storage Room A',
  },
  {
    id: 'asset-007',
    assetTag: 'IT-MN-0055',
    name: 'Dell UltraSharp 27" U2722D',
    category: 'Monitor',
    serialNumber: 'DU2722D-0055',
    purchaseDate: '2023-09-01',
    status: 'Assigned',
    location: 'Floor 3 — Engineering',
    assignedTo: 'Marcus Osei',
    assignedToId: 'EMP-1042',
    department: 'Engineering',
  },
  {
    id: 'asset-008',
    assetTag: 'IT-MN-0056',
    name: 'LG 27UL850 4K Monitor',
    category: 'Monitor',
    serialNumber: 'LG27UL850-0056',
    purchaseDate: '2024-02-14',
    status: 'Available',
    location: 'IT Storage Room B',
  },
  {
    id: 'asset-009',
    assetTag: 'IT-PR-0011',
    name: 'HP LaserJet Pro M404dn',
    category: 'Printer',
    serialNumber: 'HPLJ404-0011',
    purchaseDate: '2022-05-20',
    status: 'Assigned',
    location: 'Floor 1 — Admin',
    assignedTo: 'Admin Office',
    assignedToId: 'DEPT-ADMIN',
    department: 'Administration',
  },
  {
    id: 'asset-010',
    assetTag: 'IT-PR-0012',
    name: 'Canon imageRUNNER 2630i',
    category: 'Printer',
    serialNumber: 'CNIR2630-0012',
    purchaseDate: '2021-11-03',
    status: 'Retired',
    location: 'IT Disposal Hold',
    notes: 'End of life — awaiting disposal approval',
  },
  {
    id: 'asset-011',
    assetTag: 'IT-NW-0007',
    name: 'Cisco Catalyst 2960-X Switch',
    category: 'Networking',
    serialNumber: 'CSC2960X-0007',
    purchaseDate: '2022-08-15',
    status: 'Assigned',
    location: 'Server Room — Rack 3',
    assignedTo: 'Network Infrastructure',
    assignedToId: 'DEPT-INFRA',
    department: 'IT Infrastructure',
  },
  {
    id: 'asset-012',
    assetTag: 'IT-NW-0008',
    name: 'Ubiquiti UniFi AP AC Pro',
    category: 'Networking',
    serialNumber: 'UBQ-UAP-0008',
    purchaseDate: '2023-03-22',
    status: 'Assigned',
    location: 'Floor 2 — Ceiling Mount',
    assignedTo: 'Network Infrastructure',
    assignedToId: 'DEPT-INFRA',
    department: 'IT Infrastructure',
  },
  {
    id: 'asset-013',
    assetTag: 'IT-SV-0003',
    name: 'Dell PowerEdge R750',
    category: 'Server',
    serialNumber: 'DPER750-0003',
    purchaseDate: '2022-01-10',
    status: 'Assigned',
    location: 'Server Room — Rack 1',
    assignedTo: 'IT Infrastructure',
    assignedToId: 'DEPT-INFRA',
    department: 'IT Infrastructure',
  },
  {
    id: 'asset-014',
    assetTag: 'IT-AC-0088',
    name: 'Logitech MX Keys Keyboard',
    category: 'Accessory',
    serialNumber: 'LGT-MXKEYS-0088',
    purchaseDate: '2024-01-05',
    status: 'Available',
    location: 'IT Storage Room A',
  },
  {
    id: 'asset-015',
    assetTag: 'IT-PH-0019',
    name: 'Cisco IP Phone 8841',
    category: 'Phone',
    serialNumber: 'CSC8841-0019',
    purchaseDate: '2023-06-18',
    status: 'Assigned',
    location: 'Floor 1 — Reception',
    assignedTo: 'Reception Desk',
    assignedToId: 'EMP-0001',
    department: 'Administration',
  },
];

export const ASSIGNMENTS: Assignment[] = [
  {
    id: 'asgn-001',
    assetId: 'asset-001',
    assetTag: 'IT-LT-0041',
    assetName: 'Dell Latitude 5540',
    category: 'Laptop',
    staffName: 'Marcus Osei',
    staffId: 'EMP-1042',
    department: 'Engineering',
    dateAssigned: '2024-03-20',
    expectedReturn: '2025-03-20',
    status: 'Active',
  },
  {
    id: 'asgn-002',
    assetId: 'asset-003',
    assetTag: 'IT-LT-0043',
    assetName: 'MacBook Pro 14"',
    category: 'Laptop',
    staffName: 'Priya Nair',
    staffId: 'EMP-0987',
    department: 'Design',
    dateAssigned: '2024-01-25',
    expectedReturn: '2025-01-25',
    status: 'Overdue',
  },
  {
    id: 'asgn-003',
    assetId: 'asset-005',
    assetTag: 'IT-DT-0021',
    assetName: 'HP EliteDesk 800 G9',
    category: 'Desktop',
    staffName: 'Sandra Kimani',
    staffId: 'EMP-0321',
    department: 'Finance',
    dateAssigned: '2023-08-01',
    expectedReturn: '2025-08-01',
    status: 'Active',
  },
  {
    id: 'asgn-004',
    assetId: 'asset-007',
    assetTag: 'IT-MN-0055',
    assetName: 'Dell UltraSharp 27" U2722D',
    category: 'Monitor',
    staffName: 'Marcus Osei',
    staffId: 'EMP-1042',
    department: 'Engineering',
    dateAssigned: '2023-09-10',
    expectedReturn: '2025-09-10',
    status: 'Active',
  },
  {
    id: 'asgn-005',
    assetId: 'asset-009',
    assetTag: 'IT-PR-0011',
    assetName: 'HP LaserJet Pro M404dn',
    category: 'Printer',
    staffName: 'Admin Office',
    staffId: 'DEPT-ADMIN',
    department: 'Administration',
    dateAssigned: '2022-06-01',
    expectedReturn: '2026-06-01',
    status: 'Active',
  },
  {
    id: 'asgn-006',
    assetId: 'asset-011',
    assetTag: 'IT-NW-0007',
    assetName: 'Cisco Catalyst 2960-X Switch',
    category: 'Networking',
    staffName: 'IT Infrastructure',
    staffId: 'DEPT-INFRA',
    department: 'IT Infrastructure',
    dateAssigned: '2022-08-20',
    expectedReturn: '2027-08-20',
    status: 'Active',
  },
  {
    id: 'asgn-007',
    assetId: 'asset-013',
    assetTag: 'IT-SV-0003',
    assetName: 'Dell PowerEdge R750',
    category: 'Server',
    staffName: 'IT Infrastructure',
    staffId: 'DEPT-INFRA',
    department: 'IT Infrastructure',
    dateAssigned: '2022-01-15',
    expectedReturn: '2027-01-15',
    status: 'Active',
  },
  {
    id: 'asgn-008',
    assetId: 'asset-015',
    assetTag: 'IT-PH-0019',
    assetName: 'Cisco IP Phone 8841',
    category: 'Phone',
    staffName: 'Aisha Mensah',
    staffId: 'EMP-0001',
    department: 'Administration',
    dateAssigned: '2023-07-01',
    expectedReturn: '2025-07-01',
    status: 'Overdue',
    notes: 'Receptionist left company — pending equipment collection',
  },
  {
    id: 'asgn-009',
    assetId: 'asset-012',
    assetTag: 'IT-NW-0008',
    assetName: 'Ubiquiti UniFi AP AC Pro',
    category: 'Networking',
    staffName: 'IT Infrastructure',
    staffId: 'DEPT-INFRA',
    department: 'IT Infrastructure',
    dateAssigned: '2023-03-25',
    expectedReturn: '2028-03-25',
    status: 'Active',
  },
  {
    id: 'asgn-010',
    assetId: 'asset-002',
    assetTag: 'IT-LT-0042',
    assetName: 'Dell Latitude 5540',
    category: 'Laptop',
    staffName: 'James Okafor',
    staffId: 'EMP-1155',
    department: 'Sales',
    dateAssigned: '2024-11-01',
    expectedReturn: '2024-12-31',
    status: 'Returned',
    returnedDate: '2024-12-28',
  },
];

export const AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-04-01T08:30:00',
    action: 'Assigned',
    assetTag: 'IT-LT-0041',
    assetName: 'Dell Latitude 5540',
    performedBy: 'Admin (IT)',
    details: 'Assigned to Marcus Osei (EMP-1042) — Engineering',
  },
  {
    id: 'log-002',
    timestamp: '2026-03-31T16:45:00',
    action: 'Added',
    assetTag: 'IT-MN-0056',
    assetName: 'LG 27UL850 4K Monitor',
    performedBy: 'Admin (IT)',
    details: 'New asset added to inventory — IT Storage Room B',
  },
  {
    id: 'log-003',
    timestamp: '2026-03-31T14:10:00',
    action: 'Returned',
    assetTag: 'IT-LT-0042',
    assetName: 'Dell Latitude 5540',
    performedBy: 'Admin (IT)',
    details: 'Returned by James Okafor (EMP-1155) — Sales',
  },
  {
    id: 'log-004',
    timestamp: '2026-03-30T11:22:00',
    action: 'Flagged',
    assetTag: 'IT-LT-0044',
    assetName: 'Lenovo ThinkPad X1 Carbon',
    performedBy: 'Admin (IT)',
    details: 'Marked as Faulty — battery not charging, sent to vendor',
  },
  {
    id: 'log-005',
    timestamp: '2026-03-29T09:05:00',
    action: 'Updated',
    assetTag: 'IT-PR-0011',
    assetName: 'HP LaserJet Pro M404dn',
    performedBy: 'Admin (IT)',
    details: 'Location updated to Floor 1 — Admin',
  },
  {
    id: 'log-006',
    timestamp: '2026-03-28T15:30:00',
    action: 'Added',
    assetTag: 'IT-AC-0088',
    assetName: 'Logitech MX Keys Keyboard',
    performedBy: 'Admin (IT)',
    details: 'New accessory added — IT Storage Room A',
  },
  {
    id: 'log-007',
    timestamp: '2026-03-27T10:15:00',
    action: 'Assigned',
    assetTag: 'IT-PH-0019',
    assetName: 'Cisco IP Phone 8841',
    performedBy: 'Admin (IT)',
    details: 'Assigned to Aisha Mensah (EMP-0001) — Administration',
  },
  {
    id: 'log-008',
    timestamp: '2026-03-26T13:45:00',
    action: 'Returned',
    assetTag: 'IT-DT-0022',
    assetName: 'HP EliteDesk 800 G9',
    performedBy: 'Admin (IT)',
    details: 'Returned from Finance department — now available',
  },
];